services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:hHqxqLIMvuNqKHjzAPNwVpgqJitEJhrM@gondola.proxy.rlwy.net:41520/railway
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        value: your-secret-key-here

databases:
  - name: subomap-db
    databaseName: AIDB
    user: admin
    plan: free
