services:
  - type: web
    name: subomap-academy
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      chmod +x pre_deploy.sh
      ./pre_deploy.sh
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: "mysql://root:RlnjaHZoFYoaoxssxFHKtLFQlvwqninP@yamanote.proxy.rlwy.net:17657/railway"
      - key: SECRET_KEY
        generateValue: true
      - key: LOG_TO_STDOUT
        value: true
      - key: FLASK_ENV
        value: production

databases:
  - name: subomap-db
    databaseName: AIDB
    user: admin
    plan: free
