"""Add doc_link to Module table

Revision ID: 76a3d59c1e95
Revises: 99e3a5025538
Create Date: 2025-04-01 15:17:10.434948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a3d59c1e95'
down_revision = '99e3a5025538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('doc_link')

    # ### end Alembic commands ###
