"""add payment status

Revision ID: add_payment_status
Revises: 99e3a5025538
Create Date: 2024-03-26 16:51:35.165325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_payment_status'
down_revision = '99e3a5025538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_paid')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ### 