"""Add attempt_number and next_attempt_available to QuizResult

Revision ID: e8e06eea98c6
Revises: 
Create Date: 2025-03-25 19:22:36.685122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e06eea98c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_attempt_available', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('next_attempt_available')
        batch_op.drop_column('attempt_number')

    # ### end Alembic commands ###
